# Generated by Django 3.2.4 on 2021-06-12 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('isbn', models.CharField(db_column='ISBN', max_length=13, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('edition', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('publisher', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Book_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('professor', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('course_id', models.CharField(max_length=9)),
                ('section_id', models.CharField(blank=True, max_length=3, null=True)),
                ('have_book', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsedbookComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'UsedBook_Comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsedBookInfo',
            fields=[
                ('usedbook_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('quality', models.IntegerField()),
                ('semester', models.CharField(blank=True, max_length=4, null=True)),
                ('is_sold', models.IntegerField()),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Used_Book_Info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=20, null=True)),
                ('total_sells', models.IntegerField(blank=True, null=True)),
                ('complain_numbers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'User_Info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlphaInfo',
            fields=[
                ('isbn', models.OneToOneField(db_column='ISBN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usedbook.bookinfo')),
                ('price', models.CharField(max_length=6)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Alpha_Info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('isbn', models.OneToOneField(db_column='ISBN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usedbook.bookinfo')),
                ('author', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Author_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LibraryInfo',
            fields=[
                ('isbn', models.OneToOneField(db_column='ISBN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usedbook.bookinfo')),
                ('exist', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Library_Info',
                'managed': False,
            },
        ),
    ]
